# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: Templating
inputs:
  synchronize-pull-request-template:
    description: Whether to synchronize the pull-request template
    type: boolean
    default: true
  synchronize-security-policy:
    description: Whether to synchronize the security policy
    type: boolean
    default: true
  package-url:
    description: GitHub URL of the MQT package
    type: string
    default: ""
runs:
  using: docker
  image: action.Dockerfile
  args:
    - ${{ inputs.synchronize-pull-request-template }}
    - ${{ inputs.synchronize-security-policy }}
    - ${{ inputs.package-url }}
