name: Templating
inputs:
  package-name:
    description: The name of the MQT package
    type: string
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.package-name }}
