version: 2

formats:
  - htmlzip

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-26.04
  tools:
    python: "3.14"
  apt_packages:
    - imagemagick
    - graphviz
    - libgvplugin-neato-layout8
    - inkscape

python:
  install:
    - method: uv
      command: pip
      requirements: docs/requirements.txt
